import { Order } from "@/types/Order";

export const OrdersData: Order[] = [
  {
    orderId: 1,
    customerName: "Bob",
    orderStatus: "Picking",
    items: ["Item B"],
    createdAt: new Date("2024-12-26"),
  },
  {
    orderId: 2,
    customerName: "Alice",
    orderStatus: "Delivering",
    items: ["Item B"],
    createdAt: new Date("2025-01-22"),
  },
  {
    orderId: 3,
    customerName: "Bob",
    orderStatus: "Delivering",
    items: ["Item C", "Item B"],
    createdAt: new Date("2025-01-03"),
  },
  {
    orderId: 4,
    customerName: "Eve",
    orderStatus: "Delivered",
    items: ["Item C", "Item D", "Item B"],
    createdAt: new Date("2025-01-21"),
  },
  {
    orderId: 5,
    customerName: "Grace",
    orderStatus: "Delivered",
    items: ["Item A", "Item B"],
    createdAt: new Date("2025-01-22"),
  },
  {
    orderId: 6,
    customerName: "Charlie",
    orderStatus: "Delivering",
    items: ["Item D", "Item B"],
    createdAt: new Date("2025-01-12"),
  },
  {
    orderId: 7,
    customerName: "Eve",
    orderStatus: "Delivered",
    items: ["Item E", "Item A"],
    createdAt: new Date("2025-01-10"),
  },
  {
    orderId: 8,
    customerName: "Grace",
    orderStatus: "Delivered",
    items: ["Item D", "Item A", "Item E"],
    createdAt: new Date("2025-01-06"),
  },
  {
    orderId: 9,
    customerName: "Eve",
    orderStatus: "New",
    items: ["Item C"],
    createdAt: new Date("2025-01-08"),
  },
  {
    orderId: 10,
    customerName: "Eve",
    orderStatus: "Picking",
    items: ["Item E"],
    createdAt: new Date("2025-01-11"),
  },
  {
    orderId: 11,
    customerName: "Grace",
    orderStatus: "New",
    items: ["Item C"],
    createdAt: new Date("2025-01-21"),
  },
  {
    orderId: 12,
    customerName: "Eve",
    orderStatus: "Picking",
    items: ["Item E", "Item B", "Item D"],
    createdAt: new Date("2025-01-01"),
  },
  {
    orderId: 13,
    customerName: "David",
    orderStatus: "Picking",
    items: ["Item D", "Item E", "Item B"],
    createdAt: new Date("2025-01-13"),
  },
  {
    orderId: 14,
    customerName: "David",
    orderStatus: "New",
    items: ["Item C"],
    createdAt: new Date("2025-01-19"),
  },
  {
    orderId: 15,
    customerName: "Frank",
    orderStatus: "Delivered",
    items: ["Item D"],
    createdAt: new Date("2025-01-18"),
  },
  {
    orderId: 16,
    customerName: "Charlie",
    orderStatus: "Delivered",
    items: ["Item C", "Item E", "Item A"],
    createdAt: new Date("2025-01-17"),
  },
  {
    orderId: 17,
    customerName: "Charlie",
    orderStatus: "New",
    items: ["Item E", "Item D"],
    createdAt: new Date("2025-01-15"),
  },
  {
    orderId: 18,
    customerName: "Grace",
    orderStatus: "Picking",
    items: ["Item E"],
    createdAt: new Date("2025-01-15"),
  },
  {
    orderId: 19,
    customerName: "Eve",
    orderStatus: "Picking",
    items: ["Item E", "Item B"],
    createdAt: new Date("2025-01-12"),
  },
  {
    orderId: 20,
    customerName: "Jack",
    orderStatus: "Delivered",
    items: ["Item E"],
    createdAt: new Date("2025-01-09"),
  },
  {
    orderId: 21,
    customerName: "David",
    orderStatus: "Picking",
    items: ["Item E", "Item C", "Item B"],
    createdAt: new Date("2025-01-12"),
  },
  {
    orderId: 22,
    customerName: "Isaac",
    orderStatus: "Delivering",
    items: ["Item A"],
    createdAt: new Date("2024-12-25"),
  },
  {
    orderId: 23,
    customerName: "Grace",
    orderStatus: "Delivered",
    items: ["Item B", "Item D", "Item E"],
    createdAt: new Date("2024-12-29"),
  },
  {
    orderId: 24,
    customerName: "Frank",
    orderStatus: "Picking",
    items: ["Item C", "Item A", "Item B"],
    createdAt: new Date("2024-12-27"),
  },
  {
    orderId: 25,
    customerName: "David",
    orderStatus: "Delivered",
    items: ["Item D", "Item C"],
    createdAt: new Date("2025-01-02"),
  },
  {
    orderId: 26,
    customerName: "Alice",
    orderStatus: "New",
    items: ["Item B", "Item A", "Item C"],
    createdAt: new Date("2025-01-16"),
  },
  {
    orderId: 27,
    customerName: "Isaac",
    orderStatus: "Delivered",
    items: ["Item A"],
    createdAt: new Date("2025-01-14"),
  },
  {
    orderId: 28,
    customerName: "Jack",
    orderStatus: "Delivered",
    items: ["Item C"],
    createdAt: new Date("2024-12-30"),
  },
  {
    orderId: 29,
    customerName: "Isaac",
    orderStatus: "Delivered",
    items: ["Item A", "Item E"],
    createdAt: new Date("2025-01-08"),
  },
  {
    orderId: 30,
    customerName: "Grace",
    orderStatus: "Delivered",
    items: ["Item D"],
    createdAt: new Date("2025-01-17"),
  },
  {
    orderId: 31,
    customerName: "David",
    orderStatus: "Delivered",
    items: ["Item D", "Item E", "Item B"],
    createdAt: new Date("2025-01-16"),
  },
  {
    orderId: 32,
    customerName: "Isaac",
    orderStatus: "New",
    items: ["Item D", "Item C", "Item B"],
    createdAt: new Date("2025-01-21"),
  },
  {
    orderId: 33,
    customerName: "Grace",
    orderStatus: "Delivered",
    items: ["Item C"],
    createdAt: new Date("2025-01-15"),
  },
  {
    orderId: 34,
    customerName: "Isaac",
    orderStatus: "Delivered",
    items: ["Item C"],
    createdAt: new Date("2024-12-25"),
  },
  {
    orderId: 35,
    customerName: "Bob",
    orderStatus: "Picking",
    items: ["Item D"],
    createdAt: new Date("2025-01-06"),
  },
  {
    orderId: 36,
    customerName: "Jack",
    orderStatus: "Delivering",
    items: ["Item D", "Item C", "Item B"],
    createdAt: new Date("2025-01-12"),
  },
  {
    orderId: 37,
    customerName: "Hannah",
    orderStatus: "Delivering",
    items: ["Item E"],
    createdAt: new Date("2025-01-02"),
  },
  {
    orderId: 38,
    customerName: "Alice",
    orderStatus: "Delivered",
    items: ["Item C", "Item D"],
    createdAt: new Date("2025-01-08"),
  },
  {
    orderId: 39,
    customerName: "Alice",
    orderStatus: "Delivered",
    items: ["Item B"],
    createdAt: new Date("2025-01-05"),
  },
  {
    orderId: 40,
    customerName: "Eve",
    orderStatus: "Picking",
    items: ["Item B"],
    createdAt: new Date("2025-01-19"),
  },
  {
    orderId: 41,
    customerName: "David",
    orderStatus: "Delivering",
    items: ["Item D", "Item B", "Item A"],
    createdAt: new Date("2024-12-31"),
  },
  {
    orderId: 42,
    customerName: "Bob",
    orderStatus: "Delivering",
    items: ["Item C"],
    createdAt: new Date("2025-01-04"),
  },
  {
    orderId: 43,
    customerName: "Eve",
    orderStatus: "New",
    items: ["Item A", "Item E"],
    createdAt: new Date("2025-01-03"),
  },
  {
    orderId: 44,
    customerName: "Jack",
    orderStatus: "New",
    items: ["Item A"],
    createdAt: new Date("2025-01-12"),
  },
  {
    orderId: 45,
    customerName: "Alice",
    orderStatus: "Picking",
    items: ["Item D", "Item E"],
    createdAt: new Date("2024-12-28"),
  },
  {
    orderId: 46,
    customerName: "Eve",
    orderStatus: "New",
    items: ["Item B"],
    createdAt: new Date("2025-01-09"),
  },
  {
    orderId: 47,
    customerName: "Grace",
    orderStatus: "New",
    items: ["Item C"],
    createdAt: new Date("2025-01-06"),
  },
  {
    orderId: 48,
    customerName: "Frank",
    orderStatus: "New",
    items: ["Item B"],
    createdAt: new Date("2025-01-01"),
  },
  {
    orderId: 49,
    customerName: "Charlie",
    orderStatus: "New",
    items: ["Item D"],
    createdAt: new Date("2025-01-14"),
  },
  {
    orderId: 50,
    customerName: "Frank",
    orderStatus: "Delivering",
    items: ["Item E", "Item D", "Item A"],
    createdAt: new Date("2025-01-05"),
  },
];
